github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

codeowners:
  - path: "*"
    owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:
    [
      "docker.io/paketobuildpacks/jvm-vendors",
      "gcr.io/paketo-buildpacks/jvm-vendors",
    ]
  register: true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: gcr.io
    username: _json_key
    password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
