api = "0.10"

[buildpack]
  description = "A Cloud Native Buildpack that provides JVM vendor implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/jvm-vendors"
  id = "paketo-buildpacks/jvm-vendors"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for JVM Vendors"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/jvm-vendors/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    default = "true"
    description = "disable the low memory profile for containers with less than 1G of memory"
    launch = true
    name = "BPL_LOW_MEMORY_PROFILE_DISABLED"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "17"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the default JVM vendor"
    name = "BP_JVM_VENDOR"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the available JVM vendors"
    name = "BP_JVM_VENDORS"

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jre-adoptium"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-alibaba-dragonwell"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-alibaba-dragonwell"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-alibaba-dragonwell"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-alibaba-dragonwell"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-alibaba-dragonwell"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-amazon-corretto"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jre-azul-zulu"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jre-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "native-image-svm-bellsoft-liberica"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jre-eclipse-openj9"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "native-image-svm-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "native-image-svm-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "native-image-svm-graalvm"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "native-image-svm-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "native-image-svm-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "native-image-svm-oracle"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^8"
    id = "jdk-microsoft-openjdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^11"
    id = "jdk-microsoft-openjdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-microsoft-openjdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-microsoft-openjdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-microsoft-openjdk"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jdk-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jdk-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jdk-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jdk-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^17"
    id = "jre-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^21"
    id = "jre-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^25"
    id = "jre-sap-machine"
    patches = 1

  [[metadata.dependency-constraints]]
    constraint = "^26"
    id = "jre-sap-machine"
    patches = 1

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
